# 数据配置
data:
  data_dir: "./data"
  batch_size: 256

# 模型配置
model:
  model_type: "cnn"  # mlp, cnn, rnn, gru, resnet18, resnet50, densenet121, vit
  num_classes: 2
  dropout: 0.3
  
  # 模型特定配置
  mlp:
    hidden_dims: [2048, 1024, 1024, 256, 64]
  
  cnn:
    channels: [16, 32, 64]
    kernel_size: 3
  
  rnn:
    hidden_size: 128
    num_layers: 2
    bidirectional: true

# 训练配置
training:
  num_epochs: 18
  lr: 1e-3
  weight_decay: 1e-3
  patience: 3
  
  # 优化器设置
  optimizer: "adamw"  # adam, adamw, sgd
  scheduler: "cosine"  # cosine, step, plateau

# 交叉验证配置
cross_validation:
  use_kfold: true
  n_splits: 10
  stratified: true
  test_ratio: 0.05

# 保存和日志配置
paths:
  save_dir: "./models"
  log_dir: "./logs"
  experiment_name: null  # 如果为null，会自动生成

# GPU配置
gpu:
  gradient_accumulation_steps: 1